services:
  agentic_system:
    build: ./server
    container_name: agentic-system  
    ports:
      - "8000:8000"
    depends_on:
      sql_database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MODEL_BASE_URL: ${MODEL_BASE_URL}
      MODEL_NAME: ${MODEL_NAME}
      MODEL_API_KEY: ${MODEL_API_KEY}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL}

      EDUCATION_DATABASE_HOST: sql_database
      EDUCATION_DATABASE_PORT: 5432
      EDUCATION_DATABASE_NAME: ${EDUCATION_DATABASE_NAME}
      EDUCATION_DATABASE_USER: ${EDUCATION_DATABASE_USER}
      EDUCATION_DATABASE_PASS: ${EDUCATION_DATABASE_PASS}

      TZ: Europe/Moscow
    volumes:
      - uploads_data:/app/uploads

  # frontend:
  #   build: ./client
  #   container_name: frontend
  #   ports:
  #     - "5173:5173"
  #   working_dir: /app
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   command: sh -c "npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 5173"
  #   depends_on:
  #     - agentic_system

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.2
    restart: on-failure:0
    ports:
    - 8080:8080
    - 50051:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'cluster1'
    volumes:
      - weaviate_data:/var/lib/weaviate

  sql_database:
    image: postgres:18
    container_name: sql-database
    environment:
      POSTGRES_DB: ${EDUCATION_DATABASE_NAME}
      POSTGRES_USER: ${EDUCATION_DATABASE_USER}
      POSTGRES_PASSWORD: ${EDUCATION_DATABASE_PASS}

      TZ: Europe/Moscow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql

  t2v-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2

volumes:
  postgres_data:
  weaviate_data:
  uploads_data: